### ISSUE TITLE
Interword spacing is still zero

### ISSUE THREAD

**Issue by AndyClifton** [AndyClifton/AccessibleMetaClass#10]
An important part of the tagging of a PDF document is to ensure that the text are accurately captured in the tag structure. In Acrobat, this can be seen by opening the tag structure and going to e.g. a <P> tag. The content of this tag should look like normal text and include spaces. But it doesn't.

This bug breaks the document's accessibility.

**Comment by neingeist** [comment]
Couldn't check this with Acrobat yet, but did you check only the title section? There I see this problem on the demo PDF using `pdfinfo -struct-text`:

```
  Div "Titlepage"
    P (block)
      "SoyouwanttoreplaceyourWYSIWYGwordproces-sorwithLaTeX,but508compliancehasyoustumped?"
    Table (block)
      TBody
        TR
          TD
            "AndyClifton"
  P (block)
    "Friday17thMarch,2017"
```

Whereas I get correct spaces starting from the abstract:

```
 Sect "Abstract"
    H (block)
      "Abstract"
    P (block)
      "‘What you see is what you get’ (WYSIWYG) word pro- cessors are frequently used within organizations
 to pro- duce PDF documents that have a common look and feel. The PDFs are tagged, structured, and pass au
tomated tests for document accessibility. PDFs that are created with LATEX do not pass such tests, making 
it difficult to use LATEX in a corporate environment. This document ex- plains how LATEX can be used to pr
epare documents that can be used in a corporate environment. This is achieved by using a file source that 
can be converted in to an"
      Span (inline)
        ".rtf"
      "file, which can be read in to a WYSIWYG word pro- cessor. The same source can be used to create"
      Span (inline)
        ".pdf"
      "files that satisfy accessibility requirements. This document is intended to be used as a template a
s it contains most of the elements of a technical LATEX document, including complex document structures, lists, equations, figures and code listings."
  [...]
```

**Comment by AndyClifton** [comment]
OK, so there's a difference between that and what I see in Acrobat. All of the `P` blocks are missing spaces in Acrobat.

**Comment by neingeist** [comment]
If you look at the PDF using a text editor, there should be "( )Tj" commands for the spaces between the TJ commands for the actual text. Unfortunately I can't access my Acrobat installation just now and can't check.

**Comment by AndyClifton** [comment]
Struggling a bit with the PDF, but I think this is the abstract:

> /F75 11.9552 Tf/F76 1 Tf( )Tj/F75 11.9552 Tf 72 543.073 Td [(Abstract)]TJ
0 0.47452 0.75687 rg 0 0.47452 0.75687 RG
0 0.47452 0.75687 rg 0 0.47452 0.75687 RG
0 g 0 G
ET
1 0 0 1 72 541.5 cm
EMC
1 0 0 1 0 -18.456 cm
/P <</MCID 4>> BDC
1 0 0 1 -72 -523.044 cm
BT
/F73 9.9626 Tf/F76 1 Tf( )Tj/F73 9.9626 Tf 72 523.044 Td [(`What)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 27.387 0 Td [(you)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 17.435 0 Td [(see)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 15.212 0 Td [(is)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 9.136 0 Td [(what)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 21.858 0 Td [(you)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 17.434 0 Td [(get')]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 17.983 0 Td [(\050WYSIWYG\051)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 58.37 0 Td [(w)10(ord)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 22.865 0 Td [(pro-)]TJ
0 g 0 G
0 g 0 G
/F76 1 Tf( )Tj/F73 9.9626 Tf -207.68 -11.955 Td [(cessors)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 31.262 0 Td [(are)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 14.655 0 Td [(frequently)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 43.437 0 Td [(used)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 20.752 0 Td [(within)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 27.955 0 Td [(or)18(g)5(anizations)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 55.939 0 Td [(to)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 10.242 0 Td [(pro-)]TJ
0 g 0 G
0 g 0 G
/F76 1 Tf( )Tj/F73 9.9626 Tf -204.242 -11.956 Td [(duce)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 21.3 0 Td [(PDF)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 20.762 0 Td [(documents)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 45.658 0 Td [(that)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 17.435 0 Td [(ha)20(v)15(e)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 20.951 0 Td [(a)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 6.914 0 Td [(common)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 37.36 0 Td [(look)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 20.204 0 Td [(and)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 16.877 0 Td [(feel.)]TJ
0 g 0 G
0 g 0 G
/F76 1 Tf( )Tj/F73 9.9626 Tf -207.461 -11.955 Td [(The)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 17.983 0 Td [(PDFs)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 24.637 0 Td [(are)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 14.655 0 Td [(tagged,)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 31.541 0 Td [(structured,)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 44.822 0 Td [(and)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 16.876 0 Td [(pass)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 19.646 0 Td [(automated)]TJ
0 g 0 G
0 g 0 G
/F76 1 Tf( )Tj/F73 9.9626 Tf -170.16 -11.955 Td [(tests)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 20.204 0 Td [(for)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 14.107 0 Td [(document)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 41.783 0 Td [(accessibility)65(.)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 54.186 0 Td [(PDFs)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 24.637 0 Td [(that)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 17.434 0 Td [(are)]TJ/F76 1 Tf( )Tj/F73 9.9626 Tf 14.655 0 Td [(created)]TJ
0 g 0 G
0 g 0 G

I've looked elsewhere in the document and it appears to be the same kind of `...Tf( )Tj...` structure.

So - it looks like it's probably OK in that case?

**Comment by neingeist** [comment]
As far as I can see this is OK, the spaces (`( )Tj`) are there except in the title. But let me check in Acrobat on Monday.

**Comment by neingeist** [comment]
However, I see the same problem using Adobe Acrobat.

**Comment by AndyClifton** [comment]
@neingeist  - same comment here as to your feedback re. the document structure. Could you take a look at https://github.com/AndyClifton/CorporateLaTeX and see if the same issue pops up there, please? Thanks!
