### ISSUE TITLE
Extra line at the start of verbatim environments 

### ISSUE THREAD

**Issue by AndyClifton** [AndyClifton/AccessibleMetaClass#12]
Currently any text produced using the verbatim environment is mapped to `lstlistings` if it's a normal 'tex document. This produces an extra, blank line at the start of this environment.

**Comment by neingeist** [comment]
The verbatim environments are more broken: There's a tiny "2" next to every one of them, which is supposed to be the line numbering.

**Comment by AndyClifton** [comment]
Opened a new issue for the line numbers.
