### ISSUE TITLE
Broken PDF structure

### ISSUE THREAD

**Issue by neingeist** [AndyClifton/AccessibleMetaClass#19]
![broken-tags](https://cloud.githubusercontent.com/assets/398881/24108699/a5f196d4-0d8e-11e7-9161-5aca6d4fa23c.png)

Acrobat should highlight the whole subsubsection here in the demo PDF, but does only highlight until the sentence "For example, Figure 1 has been labeled with a tool tip." The subsubsection does contain more tags, but Acrobat cannot highlight them.

**Comment by AndyClifton** [comment]
This would appear to be a pretty major bug - correct structure is an essential part of accessibility!

**Comment by AndyClifton** [comment]
@neingeist : I may have solved this with the new template. Can you take a look at https://github.com/AndyClifton/CorporateLaTeX and tell me how that looks, please?

**Comment by AndyClifton** [comment]
Closing this as part of consolidating all of my accessibility related efforts in the [accessibiiity](https://github.com/AndyClifton/accessibility) repository.
