### ISSUE TITLE
Unknown environment \begin{subfigure} ... \end{subfigure}

### ISSUE THREAD

**Issue by jzaburunov** [AndyClifton/AccessibleMetaClass#20]
Hi! Trying to use latex2rtf package to test transform.

So when I use `$ latex2rtf DemoAccMetaClass.tex` I get this messages: 

> Latex2rtf_DemoAccMetaClass.tex:1   Including file <Latex2rtf_DemoAccMetaClass.tex>
> Latex2rtf_DemoAccMetaClass.tex:28  partial support for subfigure package
> DemoAccMetaClass.tex:93  (DemoAccMetaClass.aux)
> DemoAccMetaClass.tex:140 Unknown environment \begin{subfigure} ... \end{subfigure}
> DemoAccMetaClass.tex:140 Unknown environment \begin{subfigure} ... \end{subfigure}
> DemoAccMetaClass.tex:148 Unknown command '\alt'

latex2pdf version 2.3.8

**Comment by AndyClifton** [comment]
I'm going to close this as it's not an issue if we use pandoc.
